services:
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "50051:50051"

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    environment:
      PRODUCER_GRPC_URL: producer:50051
    depends_on:
      - producer
